In [1]:
import numpy as np
import pandas as pd

### Задание 1

In [2]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### Задание 2

In [4]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [5]:
a1 = a_centered[:,0]
a2 = a_centered[:,1]
a_centered_sp = np.dot(a1,a2)
a_centered_sp

8.0

In [6]:
N = a.shape[0]
N

5

In [7]:
final = a_centered_sp / (N - 1)
final

2.0

In [8]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

### Pandas

### Задание 1

In [9]:
authors = pd.DataFrame({'author_id': [1, 2, 3], 
                        'author_name': ['Тургенев', 'Чехов', 'Островский']}, 
                       columns=['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [10]:
book = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3],
                     'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price': [450, 300, 350, 500, 450, 370, 290]})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2

In [11]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3

In [12]:
top_5 = authors_price.nlargest(5, 'price')
top_5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4

In [13]:
df1 = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price':'min_price'})
df2 = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price':'max_price'})
df3 = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price':'mean_price'})
authors_stat=pd.concat([df1, df2, df3], axis = 1)
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

### Курсовой проект

##### Объединил все задания в одно и разделил по колонкам

In [14]:
# читаем csv с данными
project = pd.read_csv('train.csv')
project

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0     11809          27    3.0  115.027311         NaN           10.0      4   
1      3013          22    1.0   39.832524   23.169223            8.0      7   
2      8215           1    3.0   78.342215   47.671972           10.0      2   
3      2352           1    1.0   40.409907         NaN            1.0     10   
4     13866          94    2.0   64.285067   38.562517            9.0     16   
...     ...         ...    ...         ...         ...            ...    ...   
9995   1260          61    2.0   49.090728   33.272626            6.0      3   
9996  16265          27    2.0   64.307684   37.038420            9.0     13   
9997   2795         178    1.0   29.648057   16.555363            5.0      3   
9998  14561          21    1.0   32.330292   22.326870            5.0      3   
9999   7202          94    1.0   35.815476   22.301367            6.0      9   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
0           10.0       2014   0.075424         B         B        11   
1            8.0       1966   0.118537         B         B        30   
2           17.0       1988   0.025609         B         B        33   
3           22.0       1977   0.007122         B         B         1   
4           16.0       1972   0.282798         B         B        33   
...          ...        ...        ...       ...       ...       ...   
9995        12.0       1981   0.300323         B         B        52   
9996         0.0       1977   0.072158         B         B         2   
9997         5.0       1958   0.460556         B         B        20   
9998         9.0       1969   0.194489         B         B        47   
9999         9.0       1975   0.127376         B         B        43   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
0         3097         0           NaN            0        0       B   
1         6207         1        1183.0            1        0       B   
2         5261         0         240.0            3        1       B   
3          264         0           NaN            0        1       B   
4         8667         2           NaN            0        6       B   
...        ...       ...           ...          ...      ...     ...   
9995     10311         6           NaN            1        9       B   
9996       629         1           NaN            0        0       A   
9997      4386        14           NaN            1        5       B   
9998      8004         3         125.0            3        5       B   
9999      8429         3           NaN            3        9       B   

              Price  
0     305018.871089  
1     177734.553407  
2     282078.720850  
3     168106.007630  
4     343995.102962  
...             ...  
9995  119367.455796  
9996  199715.148807  
9997  165953.912580  
9998  171842.411855  
9999  177685.627486  

[10000 rows x 20 columns]

### Rooms 

In [15]:
min_rooms = project.nsmallest(1, 'Rooms')
min_rooms

# 0 комнат при 38 квадратах - скорее всего данные были пропущены или имеется ввиду что-то другое,
# так как если выбрать 10 пунктов, то 8 из них будут содержать цифру "0"
# предварительно можно сделать выводы, что показатели, где Square = 0 и LifeSquare = NaN - нежилые помещения

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
2194  3159          88    0.0  38.697117   19.345131            9.0      9   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
2194        16.0       1982   0.127376         B         B        43   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
2194      8429         3           NaN            3        9       B   

              Price  
2194  158998.110646

In [16]:
max_rooms = project.nlargest(1, 'Rooms')
max_rooms

# 3 квартиры с наибольшим числом комнат - очень странные
# квартира с id = 8491 - не могу найти сходств и совпадений
# квартира с id = 5927 и 14865 - возможно, данные перепутаны с KitchenSquare

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
6088  8491           1   19.0  42.006046   21.779288            7.0     17   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
6088        17.0       2014   0.007122         B         B         1   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
6088       264         0           NaN            0        1       B   

             Price  
6088  78364.616704

In [17]:
mean_rooms = project['Rooms'].mean()
mean_rooms

# данные не считаю релевентными, так как есть много аномальных данных, которые предварительно стоит очистить

1.8905

In [18]:
project['Rooms'].unique()

# Самый интересный пункт - 0 комнат

array([ 3.,  1.,  2.,  4.,  5., 10.,  0., 19.,  6.])

### Square

In [19]:
min_square = project.nsmallest(1, 'Square')
min_square

# квартиры с 1 по 5,49 квадратов - считаю аномальными, так как чисто физически жить в них невозможно.
# особенно аномальноый считаю первые 20

Id  DistrictId  Rooms    Square  LifeSquare  KitchenSquare  Floor  \
7470  14786           1    1.0  1.136859    4.525736            1.0      3   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
7470         1.0       1977   0.007122         B         B         1   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
7470       264         0           NaN            0        1       B   

              Price  
7470  181434.825589

In [20]:
max_square = project.nlargest(1, 'Square')
max_square

# 2 помещения аномально большие, скорее всего производственные помещения

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
9229  11602          30    2.0  641.065193  638.163193           10.0     20   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
9229        19.0       2019   0.000078         B         B        22   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
9229      6398       141        1046.0            3       23       B   

              Price  
9229  133529.681562

In [21]:
mean_square = project['Square'].mean()
mean_square

# по хорошему, классифицировать помещения на жилые и нет, чтобы точно понимать, кто есть кто

56.315775197935615

In [22]:
project['Square'].unique()

array([115.02731063,  39.83252387,  78.34221507, ...,  29.64805682,
        32.33029238,  35.81547647])

### Floor

In [23]:
min_floor = project.nsmallest(1, 'Floor') 
min_floor

# аномалий не заметил

Id  DistrictId  Rooms    Square  LifeSquare  KitchenSquare  Floor  \
6  8864          44    1.0  33.93875    21.77293            9.0      1   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
6        12.0       1968   0.232205         B         B        24      4860   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
6         1          80.0            0        3       B  142402.739272

In [24]:
max_floor = project.nlargest(1, 'Floor')
max_floor

# аномалий не заметил

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
4987  1674          76    2.0  74.344672   41.044132            5.0     42   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
4987        48.0       2016        0.0         B         B         7   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
4987      1660        39        1786.0            1        5       B   

              Price  
4987  411691.504766

In [25]:
mean_floor = project['Floor'].mean()
mean_floor

# аномалий не заметил

8.5267

In [26]:
project['Floor'].unique()

# аномалий не заметил, кроме отсутствия продаж на этажах: 29, 30, 34, 35, 36, 38, 39, 40, 41 (скорее это как интересный факт)

array([ 4,  7,  2, 10, 16,  9,  1,  8, 12,  3,  5,  6, 11, 18, 13, 21, 22,
       15, 17, 14, 23, 19, 20, 26, 25, 27, 31, 24, 28, 32, 33, 42, 37])


### HouseFloor

In [27]:
# почему эта колонка float?

min_house_floor = project.nsmallest(1, 'HouseFloor')
min_house_floor

# из выборки 40 минимальных - этажей было 0, хотя дома имеют несколько этаже из колонки Floor

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
24  4717          27    1.0  44.203947         NaN            0.0      2   

    HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
24         0.0       1977   0.072158         B         B         2       629   

    Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
24         1           NaN            0        0       A  135466.559958

In [28]:
max_house_floor = project.nlargest(1, 'HouseFloor') 
max_house_floor

# аномалий не заметил

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
1678  78          30    2.0  65.773749   66.811789            1.0      8   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
1678       117.0       1977   0.000078         B         B        22   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
1678      6398       141        1046.0            3       23       B   

             Price  
1678  207248.37052

In [29]:
mean_house_floor = project['HouseFloor'].mean()
mean_house_floor

# аномалий не заметил

12.6094

In [30]:
project['HouseFloor'].unique()

# аномалий не заметил

array([ 10.,   8.,  17.,  22.,  16.,   9.,  12.,  20.,  14.,  24.,   5.,
         0.,   1.,   3.,   4.,   6.,   7.,  25.,  21.,  11.,   2.,  23.,
        19.,  15.,  18.,  32.,  45.,  30.,  99.,  40.,  44.,  13.,  39.,
        28.,  27.,  37., 117.,  31.,  48.,  47.,  29.,  36.,  38.,  26.])

### HouseYear

In [31]:
min_house_year = project.nsmallest(10, 'HouseYear')
min_house_year

# аномалий не заметил

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
6794  13288         161    1.0   50.808925   15.920343           20.0      8   
2066  14556         183    4.0  151.150660   98.187482           23.0      6   
2795   2085         161    1.0   63.293079   29.389815           18.0      3   
6250   6751         172    2.0   56.172364   28.384213            7.0      8   
7610   7920         183    3.0  102.964468   48.322107           14.0      4   
485   13872         189    2.0   54.751367   31.515082           10.0      2   
1572  10439         104    1.0   35.507738   20.312725            4.0      6   
7867  15193         195    3.0   75.564709   44.872616            9.0      5   
2093  10919         190    2.0   47.489415   35.564479            4.0      5   
3026  12229         180    2.0   76.083312   48.026246           14.0      6   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
6794         9.0       1910   0.014423         B         B        19   
2066         7.0       1912   0.037316         B         B        32   
2795         9.0       1912   0.014423         B         B        19   
6250         6.0       1914   0.000000         B         B         7   
7610         6.0       1916   0.037316         B         B        32   
485          4.0       1917   0.000078         B         B        22   
1572         5.0       1917   0.000078         B         B        22   
7867         7.0       1917   0.015017         B         B        17   
2093         5.0       1918   0.000000         B         B        30   
3026         5.0       1918   0.037316         B         B        32   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
6794      3806         4           NaN            0        3       B   
2066      6748        93         562.0            4       10       B   
2795      3806         4           NaN            0        3       B   
6250      1660        39        1786.0            1        5       B   
7610      6748        93         562.0            4       10       B   
485       6398       141        1046.0            3       23       B   
1572      6398       141        1046.0            3       23       B   
7867      3079        59        2890.0            0        8       B   
2093      7538        87        4702.0            5        5       B   
3026      6748        93         562.0            4       10       B   

              Price  
6794  287954.720682  
2066  284884.959104  
2795  262279.813915  
6250  423580.477982  
7610  284608.939261  
485    69623.753191  
1572  236830.764637  
7867  486057.129888  
2093  537979.657509  
3026  431701.914829

In [32]:
max_house_year = project.nlargest(1, 'HouseYear') 
max_house_year

# 20052011 - скорее всего год, день, месяц
# 4968 - пока для меня загадка

Id  DistrictId  Rooms    Square  LifeSquare  KitchenSquare  Floor  \
9163  10814         109    1.0  37.26507   20.239714            9.0      9   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
9163        12.0   20052011    0.13633         B         B        30   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
9163      6141        10         262.0            3        6       B   

              Price  
9163  254084.534396

In [33]:
mean_house_year = project['HouseYear'].mean() 
mean_house_year

# изза максимальных годов (где год, день, месяц записаны как год) данные нерелевантны

3990.1663

In [34]:
project['HouseYear'].unique()

array([    2014,     1966,     1988,     1977,     1972,     1968,
           1986,     2008,     1978,     2012,     1969,     2003,
           1981,     1962,     2015,     2018,     1976,     1985,
           1960,     2019,     1974,     1956,     1963,     1961,
           1979,     2006,     1953,     1973,     1982,     1965,
           2007,     2013,     1983,     1995,     1971,     2017,
           1964,     1991,     1990,     2016,     2011,     1984,
           1993,     1997,     2009,     1975,     2010,     1987,
           1935,     1970,     1967,     1989,     1959,     1996,
           2005,     1994,     1958,     2004,     1998,     1992,
           1980,     2000,     2002,     1954,     2001,     1999,
           1917,     1955,     1957,     1934,     2020,     1932,
           1942,     1940,     1937,     1941,     1939,     1931,
           1951,     1912,     1918,     1952,     1919,     1936,
           1930,     1938,     1950,     1933,     1929,     1

### Social_1

In [35]:
min_social_1 = project.nsmallest(1, 'Social_1')
min_social_1


# Понятия не имею, что это за показатель - не могу сказать, аномалия тут или все хорошо
# Интересный факт, что DistrictId = 23 и 93 - всегда Social_1 и Social_2 = 0 и 168 соответственно и очень много NaN в LifeSquare

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
38  7679          23    2.0  55.521797         NaN            0.0      3   

    HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
38         4.0       1977   0.034656         B         B         0       168   

    Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2         Price  
38         0           NaN            0        0       B  93217.752924

In [36]:
max_social_1 = project.nlargest(1, 'Social_1')
max_social_1

# Понятия не имею, что это за показатель - не могу сказать, аномалия тут или все хорошо
# DistrictId = 12, 13 и 57 - имеют самые высокие показатели

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
238  557          12    2.0  57.154361   35.821952            9.0      9   

     HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
238        14.0       1995   0.090799         B         B        74     19083   

     Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
238         2           NaN            5       15       B  239606.501593

In [37]:
mean_social_1 = project['Social_1'].mean()
mean_social_1

# Понятия не имею, что это за показатель - не могу сказать, аномалия тут или все хорошо

24.687

In [38]:
project['Social_1'].unique()

# Понятия не имею, что это за показатель - не могу сказать, аномалия тут или все хорошо

array([11, 30, 33,  1, 35, 24, 37,  5, 42, 43,  8, 53, 46, 26, 23, 19,  2,
       38, 50, 15,  6,  4, 25,  0, 21, 66, 52, 20, 28, 36, 16, 49, 27,  9,
       41, 47, 39, 22, 18, 32, 34, 14, 31, 13, 17, 74, 29, 10, 12,  3,  7])

### Social_2

In [39]:
min_social_2 = project.nsmallest(1, 'Social_2')
min_social_2

# Интересный факт, что DistrictId = 23 и 93 - всегда Social_1 и Social_2 = 0 и 168 соответственно и очень много NaN в LifeSquare

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
38  7679          23    2.0  55.521797         NaN            0.0      3   

    HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
38         4.0       1977   0.034656         B         B         0       168   

    Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2         Price  
38         0           NaN            0        0       B  93217.752924

In [40]:
max_social_2 = project.nlargest(1, 'Social_2')
max_social_2

# Понятия не имею, что это за показатель - не могу сказать, аномалия тут или все хорошо
# DistrictId = 12, 13 и 57 - имеют самые высокие показатели

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
238  557          12    2.0  57.154361   35.821952            9.0      9   

     HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
238        14.0       1995   0.090799         B         B        74     19083   

     Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
238         2           NaN            5       15       B  239606.501593

In [41]:
mean_social_2 = project['Social_2'].mean()
mean_social_2

5352.1574

In [42]:
project['Social_2'].unique()

array([ 3097,  6207,  5261,   264,  8667,  5776,  4860,  7687,  1564,
        9292,  8429, 10621,  5288,  1497, 14892,  9515,  4439,  5212,
        3889,  5067,  3806,   629,  4788, 12238,   388,   475,  2787,
        3975,  1437,   915,  7976,  5648,   168,  4231, 10573,  5613,
        6856, 11217,  2738,  7287,  7077,  4635,  3856,  7538,  4756,
        5731, 10055,  2748,  5469,   469,  3433, 11395, 10309,  5992,
       10311,  7960,  5664,  3293,  1892,  6558,  8004,  5487,  1952,
        6714, 10418, 11319,  6398,  7651,  3893,  4048,  3374,  4789,
        3746,  6533,  5889,  7759,  7425,  4346,  4378,  2940,  7715,
        1227,  5735,  7065,  7614,  4386,  5285,  5569,  6748,  2514,
        6564, 13670,  3478,  6119,  3379,  2423,  4798, 19083,  4017,
        8647,  1986,  4472,  3369,  2733,  6783,  5011,  4583,  2370,
        3151,  4724,  5027,  7010,  6566,  5148,  6141,  3594,  6746,
        6149,  2277,  2398,  3079,  2270,  5562,  1768,  6137,  5048,
        2810,   662,


### Social_3

In [43]:
min_social_3 = project.nsmallest(1, 'Social_3')
min_social_3



Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0  11809          27    3.0  115.027311         NaN           10.0      4   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0        10.0       2014   0.075424         B         B        11      3097   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
0         0           NaN            0        0       B  305018.871089

In [44]:
max_social_3 = project.nlargest(1, 'Social_3')
max_social_3

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
106  12997           4    3.0  75.128389   52.754246            8.0      9   

     HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
106         9.0       1956   0.000078         B         B        22      6398   

     Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
106       141        1046.0            3       23       B  574631.334051

In [45]:
mean_social_3 = project['Social_3'].mean()
mean_social_3

8.0392

In [46]:
project['Social_3'].nunique()

30

### Healthcare_1

In [47]:
min_health_care_1 = project.nsmallest(1, 'Healthcare_1')
min_health_care_1

# Часто встречаются 128, 9 ,93

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
8420  9944          23    3.0  78.062848         NaN            1.0     14   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
8420        17.0       2017   0.014334         B         B         2   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
8420       528         0           0.0            0        0       B   

              Price  
8420  431238.467011

In [48]:
max_health_care_1 = project.nlargest(1, 'Healthcare_1')
max_health_care_1

# Часто стречаемый 155 DistricId

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
777  9290         155    1.0  32.651943   23.927309            5.0      3   

     HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
777         9.0       1967   0.042307         B         B        17      2810   

     Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
777         9        4849.0            3        6       B  185878.370299

In [49]:
mean_health_care_1 = project['Healthcare_1'].mean()
mean_health_care_1

1142.9044598231449

In [50]:
project['Healthcare_1'].unique()

# есть отсутствующие данные

array([  nan, 1183.,  240., 2078.,   80.,  176.,  540., 2620.,   30.,
       1937., 1130.,  705., 1970.,  520.,  770., 1020., 1322., 1340.,
       1940., 2300.,  320., 2301., 3300., 4702., 2857.,  145., 2643.,
       1406.,  350.,  628., 1548.,  125., 1430., 2672.,  900., 1145.,
       1046.,  620., 4087.,   75., 1015.,  830.,  229.,  165., 1036.,
        990., 1084.,  750.,  645.,  562., 2729.,  100.,   32.,  800.,
        810., 1450., 4129.,  920.,  730., 2715., 1308.,   46., 4508.,
       1894., 1575.,  262.,  192., 1547., 1994., 2890., 2500.,  370.,
        325., 4849.,   35., 1815., 3855., 1786.,  200.,    0.])

### Helthcare_2

In [51]:
min_health_care_2 = project.nsmallest(10, 'Helthcare_2')
min_health_care_2



Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0   11809          27    3.0  115.027311         NaN           10.0      4   
3    2352           1    1.0   40.409907         NaN            1.0     10   
4   13866          94    2.0   64.285067   38.562517            9.0     16   
6    8864          44    1.0   33.938750   21.772930            9.0      1   
8    9951           1    1.0   46.887892   44.628132            1.0     12   
9    8094           6    3.0   79.867477   75.085125            1.0      3   
10    535           2    3.0   74.199049   44.735889           10.0      5   
18   4581           1    1.0   47.582480         NaN            1.0     16   
23  13427         103    1.0   38.174328   23.123014            9.0      6   
24   4717          27    1.0   44.203947         NaN            0.0      2   

    HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0         10.0       2014   0.075424         B         B        11      3097   
3         22.0       1977   0.007122         B         B         1       264   
4         16.0       1972   0.282798         B         B        33      8667   
6         12.0       1968   0.232205         B         B        24      4860   
8         20.0       1977   0.007122         B         B         1       264   
9         17.0       2014   0.243205         B         B         5      1564   
10        14.0       2008   0.035145         B         B        42      9292   
18        16.0       1977   0.007122         B         B         1       264   
23        12.0       1969   0.014423         B         B        19      3806   
24         0.0       1977   0.072158         B         B         2       629   

    Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
0          0           NaN            0        0       B  305018.871089  
3          0           NaN            0        1       B  168106.007630  
4          2           NaN            0        6       B  343995.102962  
6          1          80.0            0        3       B  142402.739272  
8          0           NaN            0        1       B  160400.401732  
9          0         540.0            0        0       B  194756.023945  
10         3        2620.0            0        3       B  512797.373401  
18         0           NaN            0        1       B  128803.593810  
23         4           NaN            0        3       B  194273.044555  
24         1           NaN            0        0       A  135466.559958

In [52]:
max_health_care_2 = project.nlargest(10, 'Helthcare_2')
max_health_care_2

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
178   14798           0    3.0   69.462849   47.855320            7.0      2   
179    8974          54    2.0   90.144106   91.796522            1.0     10   
273   15853          54    3.0   58.703834   41.700194            5.0      3   
476    7366          54    2.0   78.810631         NaN            0.0      6   
490    1601          84    4.0   92.614973   68.503454            9.0      2   
854   11426           0    2.0   56.724377   32.602235            8.0      9   
895    4645          54    2.0   76.312851         NaN            0.0     14   
988   15694          54    2.0   75.549935   77.188447            1.0      5   
1056  11243           0    1.0   46.574439   21.552668           10.0     11   
1109  15157          54    1.0  106.239622   83.296167           17.0     26   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
178          9.0       1973   0.006076         B         B        30   
179          9.0       2017   0.006076         B         B        30   
273          5.0       1967   0.006076         B         B        30   
476          0.0       1977   0.006076         B         B        30   
490          5.0       1955   0.006076         B         B        30   
854         12.0       1982   0.006076         B         B        30   
895          0.0       1977   0.006076         B         B        30   
988          1.0       2015   0.006076         B         B        30   
1056        19.0       2011   0.006076         B         B        30   
1109        37.0       2009   0.006076         B         B        30   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
178       5285         0         645.0            6        6       B   
179       5285         0         645.0            6        6       B   
273       5285         0         645.0            6        6       B   
476       5285         0         645.0            6        6       B   
490       5285         0         645.0            6        6       B   
854       5285         0         645.0            6        6       B   
895       5285         0         645.0            6        6       B   
988       5285         0         645.0            6        6       B   
1056      5285         0         645.0            6        6       B   
1109      5285         0         645.0            6        6       B   

              Price  
178   182373.324831  
179   502813.772665  
273   246473.438829  
476   377637.066155  
490   422341.994774  
854   164687.824957  
895   466730.805333  
988   397618.124121  
1056  102434.333556  
1109  274139.065875

In [53]:
mean_health_care_2 = project['Helthcare_2'].mean()
mean_health_care_2

1.3195

In [54]:
project['Helthcare_2'].nunique()

7

### Shops_1

In [55]:
min_shops = project.nsmallest(1, 'Shops_1')
min_shops

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0  11809          27    3.0  115.027311         NaN           10.0      4   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0        10.0       2014   0.075424         B         B        11      3097   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
0         0           NaN            0        0       B  305018.871089

In [56]:
max_shops = project.nlargest(1, 'Shops_1')
max_shops

# Встречается чаще всего 30 DistricId с наибольшим кол-вом магазинов

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
106  12997           4    3.0  75.128389   52.754246            8.0      9   

     HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
106         9.0       1956   0.000078         B         B        22      6398   

     Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
106       141        1046.0            3       23       B  574631.334051

In [57]:
mean_shops = project['Shops_1'].mean()
mean_shops

4.2313

In [58]:
project['Shops_1'].nunique()

16

### Price

In [59]:
min_price = project.nsmallest(1, 'Price')
min_price

# Чаще всего встречается 23 DistricId

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
1319  13237         144    2.0  51.726692   30.547287            8.0      2   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
1319        14.0       1988   0.306977         B         B        27   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
1319      5148        14        1575.0            5        7       B   

             Price  
1319  59174.778028

In [60]:
max_price = project.nlargest(1, 'Price')
max_price

# Аномалий не нашел

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
8803  13226          73    2.0  73.210349         NaN            1.0     16   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
8803        17.0       2019   0.042032         B         B        37   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
8803      6856        84        1940.0            2        5       B   

             Price  
8803  633233.46657

In [61]:
mean_price =  project['Price'].mean()
mean_price

214138.8573987389

In [62]:
project['Price'].unique()

array([305018.87108941, 177734.55340714, 282078.72085004, ...,
       165953.91258031, 171842.41185487, 177685.62748649])

### Убираю пропуски в данных

пропуски в данных только в двух колонках

In [63]:
project[project['Healthcare_1'].notnull()]

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
1      3013          22    1.0  39.832524   23.169223            8.0      7   
2      8215           1    3.0  78.342215   47.671972           10.0      2   
5      5804          99    3.0  62.528465   47.103833            6.0      9   
6      8864          44    1.0  33.938750   21.772930            9.0      1   
7     13072          59    2.0  50.391814   32.893256            8.0      8   
...     ...         ...    ...        ...         ...            ...    ...   
9990  10635          21    1.0  18.983962   11.419796            2.0      1   
9991  11173           6    2.0  62.648779         NaN            0.0      6   
9992  11753          37    2.0  50.902724   27.159548            6.0      4   
9994   4356           9    1.0  43.303458   21.519087            8.0     12   
9998  14561          21    1.0  32.330292   22.326870            5.0      3   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
1            8.0       1966   0.118537         B         B        30   
2           17.0       1988   0.025609         B         B        33   
5            9.0       1972   0.012339         B         B        35   
6           12.0       1968   0.232205         B         B        24   
7           17.0       1986   0.019509         B         B        37   
...          ...        ...        ...       ...       ...       ...   
9990         5.0       1967   0.194489         B         B        47   
9991        17.0       1977   0.243205         B         B         5   
9992         9.0       1972   0.127812         B         B        28   
9994        14.0       1992   0.161532         B         B        25   
9998         9.0       1969   0.194489         B         B        47   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
1         6207         1        1183.0            1        0       B   
2         5261         0         240.0            3        1       B   
5         5776         1        2078.0            2        4       B   
6         4860         1          80.0            0        3       B   
7         7687        11         176.0            5        5       B   
...        ...       ...           ...          ...      ...     ...   
9990      8004         3         125.0            3        5       B   
9991      1564         0         540.0            0        0       B   
9992      7287         5         320.0            1        3       B   
9994      5648         1          30.0            2        4       B   
9998      8004         3         125.0            3        5       B   

              Price  
1     177734.553407  
2     282078.720850  
5     161044.944138  
6     142402.739272  
7     326174.175191  
...             ...  
9990  112411.221700  
9991  182625.548872  
9992  196641.468817  
9994  136744.340827  
9998  171842.411855  

[5202 rows x 20 columns]

In [64]:
project[project['LifeSquare'].notnull()]

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
1      3013          22    1.0  39.832524   23.169223            8.0      7   
2      8215           1    3.0  78.342215   47.671972           10.0      2   
4     13866          94    2.0  64.285067   38.562517            9.0     16   
5      5804          99    3.0  62.528465   47.103833            6.0      9   
6      8864          44    1.0  33.938750   21.772930            9.0      1   
...     ...         ...    ...        ...         ...            ...    ...   
9995   1260          61    2.0  49.090728   33.272626            6.0      3   
9996  16265          27    2.0  64.307684   37.038420            9.0     13   
9997   2795         178    1.0  29.648057   16.555363            5.0      3   
9998  14561          21    1.0  32.330292   22.326870            5.0      3   
9999   7202          94    1.0  35.815476   22.301367            6.0      9   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
1            8.0       1966   0.118537         B         B        30   
2           17.0       1988   0.025609         B         B        33   
4           16.0       1972   0.282798         B         B        33   
5            9.0       1972   0.012339         B         B        35   
6           12.0       1968   0.232205         B         B        24   
...          ...        ...        ...       ...       ...       ...   
9995        12.0       1981   0.300323         B         B        52   
9996         0.0       1977   0.072158         B         B         2   
9997         5.0       1958   0.460556         B         B        20   
9998         9.0       1969   0.194489         B         B        47   
9999         9.0       1975   0.127376         B         B        43   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
1         6207         1        1183.0            1        0       B   
2         5261         0         240.0            3        1       B   
4         8667         2           NaN            0        6       B   
5         5776         1        2078.0            2        4       B   
6         4860         1          80.0            0        3       B   
...        ...       ...           ...          ...      ...     ...   
9995     10311         6           NaN            1        9       B   
9996       629         1           NaN            0        0       A   
9997      4386        14           NaN            1        5       B   
9998      8004         3         125.0            3        5       B   
9999      8429         3           NaN            3        9       B   

              Price  
1     177734.553407  
2     282078.720850  
4     343995.102962  
5     161044.944138  
6     142402.739272  
...             ...  
9995  119367.455796  
9996  199715.148807  
9997  165953.912580  
9998  171842.411855  
9999  177685.627486  

[7887 rows x 20 columns]

In [ ]:
# надеюсь, все верно